name: main

on:
  push:
    branches:
      - main
      - dev
      - release/*
  workflow_dispatch:

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: setup repo
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v3

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: log params
        run: |
          echo node version = $(node --version)
          echo pnpm version = $(pnpm --version)

      - name: install
        run: pnpm i

      - name: build
        run: pnpm build:all

      - name: check source types
        run: pnpm typecheck:src:all

      - name: check test types
        run: pnpm typecheck:test:all

      - name: lint check
        run: pnpm lint:check:all

      - name: format check
        run: pnpm format:check:all

      - name: test
        run: pnpm test:all